<?php

/**
 * This is the model base class for the table "follow".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Follow".
 *
 * Columns in table "follow" available as properties of the model,
 * followed by relations of table "follow" available as properties of the model.
 *
 * @property integer $id_follower
 * @property integer $id_followed
 *
 * @property User $idFollowed
 * @property User $idFollower
 */
abstract class BaseFollow extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'follow';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Follow|Follows', $n);
	}

	public static function representingColumn() {
		return array(
			'id_follower',
			'id_followed',
		);
	}

	public function rules() {
		return array(
			array('id_follower, id_followed', 'required'),
			array('id_follower, id_followed', 'numerical', 'integerOnly'=>true),
			array('id_follower, id_followed', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idFollowed' => array(self::BELONGS_TO, 'User', 'id_followed'),
			'idFollower' => array(self::BELONGS_TO, 'User', 'id_follower'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_follower' => null,
			'id_followed' => null,
			'idFollowed' => null,
			'idFollower' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_follower', $this->id_follower);
		$criteria->compare('id_followed', $this->id_followed);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}